[package]
name = "rustymonkey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
as-any = "0.3.1"
dyn-clone = "1.0.17"
whoami = "1.5.1"
